// Owner: Reach & Data (initial setup)
// Root MaterialApp + bottom-nav routing.
//
// Note: lib/main.dart is intentionally not in the repo — it gets generated by
// `flutter create`. After running it, replace its body with:
//
//   import 'package:flutter/material.dart';
//   import 'package:flutter_riverpod/flutter_riverpod.dart';
//   import 'app.dart';
//   void main() => runApp(const ProviderScope(child: MistakeTrackerApp()));

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'ui/home_screen.dart';
import 'ui/insights_screen.dart';
import 'ui/settings_screen.dart';
import 'state/providers.dart';

class MistakeTrackerApp extends StatelessWidget {
  const MistakeTrackerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MistakeTracker',
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.indigo),
      home: const _RootShell(),
    );
  }
}

class _RootShell extends ConsumerStatefulWidget {
  const _RootShell();

  @override
  ConsumerState<_RootShell> createState() => _RootShellState();
}

class _RootShellState extends ConsumerState<_RootShell> {
  int _index = 0;

  static const _screens = <Widget>[
    HomeScreen(),
    InsightsScreen(),
    SettingsScreen(),
  ];

  @override
  void initState() {
    super.initState();
    // Initialize notifier after the first frame so ProviderScope is ready.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final notifier = ref.read(notifierProvider);
      notifier.init();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _screens[_index],
      bottomNavigationBar: NavigationBar(
        selectedIndex: _index,
        onDestinationSelected: (i) => setState(() => _index = i),
        destinations: const [
          NavigationDestination(icon: Icon(Icons.home), label: 'Home'),
          NavigationDestination(icon: Icon(Icons.insights), label: 'Insights'),
          NavigationDestination(icon: Icon(Icons.settings), label: 'Settings'),
        ],
      ),
    );
  }
}
